package com.hugmount.helloboot.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2022-04-11T14:49:15.831+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://cxf.helloboot.hugmount.com/", name = "HelloService")
public interface HelloService {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://cxf.helloboot.hugmount.com/", className = "com.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://cxf.helloboot.hugmount.com/", className = "com.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String sayHello(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
